#!/bin/bash

start=$(date +%s.%N)
# Add permissions: chmod +x script.sh
# Run script: ./script.sh

# Remove the csv files autogenerated from previous run & pictures
rm -f csvs/*
rm -f plots/csvs/*

# Compile the Java program
javac -cp atom-1.14.jar src/Main.java src/NoiseAgent.java src/InformedAgent.java

# For loop for our simulations
# Set the number of times to repeat the commands (number of simulations)
n=5
days=100
aggressivity=10
persons=200
informed=2 # This is percentage of informed

javaPart() {
  local i=$1

  # Run the program and print the output to prices.csv
  # Require 4 arguments: NUMBER_OF_PERSONS, PERCENTAGE_OF_INFORMED, AGGRESSIVITY, DAYS_OF_SIMULATION
  java -classpath "C:\Users\dant\Desktop\Master-Thesis\src;C:\Users\dant\Desktop\Master-Thesis\atom-1.14.jar" Main "$persons" "$informed" "$aggressivity" "$days" "$i"
  cat "csvs/data$i.csv" | grep "^Price" > "plots/csvs/prices$i.csv"
  cat "csvs/data$i.csv" | grep "^\(Agent\|Day\).*" > "plots/csvs/agents$i.csv"
  sed -i '/noname/d' "plots/csvs/prices$i.csv"
}

pythonGraphMetricsPart() {
  echo "Start Python Computation (Network metrics part)..."

  # Run the Python program for creation
  python plots/monte-carlo/graph_metrics.py $n $persons $informed
  echo -e "Metrics graphs was generated. \n"
}

pythonAgentCashPart() {
  echo "Start Python Computation (Agents' Cash Part)..."

  # Run the Python program for plotting agents' cash
  python plots/monte-carlo/agent_cash.py $n $persons $informed $days
  echo -e "Agents' cash evolution graph was generated. \n"
}

pythonLaplacianMetricsPart() {
  echo "Start Python Computation (Laplacian Metrics Part)..."

  # Run the Python program for computing laplacian metrics
  python plots/monte-carlo/laplacian_metrics.py $n $persons $informed
  echo -e "Laplacian graph was generated. \n"
}

pythonGephiGraphs() {
  echo "Start Python Computation (Graph Gephi)..."

  # Run the Python program for computing graph complex metrics
  python plots/monte-carlo/gephi_graphs.py $n
  echo -e "Graph gephi was generated. \n"
}

echo "Start Java Simulation..."
for i in $(seq 1 $n); do
    javaPart "$i" &
done
wait

pythonGraphMetricsPart
pythonAgentCashPart
pythonLaplacianMetricsPart

# Use this only for generating gml files
#pythonGephiGraphs

end=$(date +%s.%N)
runtime=$(python -c "print(${end} - ${start})")

echo "Runtime was $runtime seconds."

# For Ubuntu
# java -cp "atom-1.14.jar:." atomSimulation.Main 200 5 10 100
# javac -cp "atom-1.14.jar:." -d . application/src/atomSimulation/Main.java application/src/atomSimulation/InformedAgent.java application/src/atomSimulation/NoiseAgent.java
