#!/bin/bash

start=$(date +%s.%N)
# Add permissions: chmod +x script.sh
# Run script: ./script.sh

# Remove the csv files autogenerated from previous run
rm -f "PIN_mean.csv"
rm -f "assortativity_mean.csv"
rm -f "bipartivity_mean.csv"
rm -f "plot_correlation_1.png"
rm -f "plot_correlation_2.png"

# Compile the Java program
javac -cp atom-1.14.jar application/src/atomSimulation/Main.java application/src/atomSimulation/NoiseAgent.java application/src/atomSimulation/InformedAgent.java

# For loop for our simulations
# Set the number of times to repeat the commands (number of simulations)
n=2

simulation() {
   local i=$1
   echo "Start Java Simulation $i..."

   # Run the program and print the output to prices.csv
   # Require 4 arguments: NUMBER_OF_PERSONS, PERCENTAGE_OF_INFORMED, AGGRESSIVITY, DAYS_OF_SIMULATION
   java -classpath "C:\Users\dant\Desktop\Master-Thesis\application\src;C:\Users\dant\Desktop\Master-Thesis\atom-1.14.jar" atomSimulation.Main 200 5 10 100
   cat data.csv | grep "^\(Price\|Day\).*" > plots/prices.csv

   echo "Start Python Computation $i..."
   # Run the Python programs for creation
   python plots/monte-carlo/PIN_mean_creation.py
   echo "PIN csv finished."
   python plots/monte-carlo/assortativity_mean_creation.py
   echo "Assortativity csv finished."
   python plots/monte-carlo/bipartivity_mean_creation.py
   echo -e "Bipartivity csv finished. \n"
}

for i in $(seq 1 $n); do
    simulation "$i"
done
wait

# Run the Python program for computation & plot correlations
echo "Monte Carlo done. Start merging!"
python plots/monte-carlo/correlation_plots.py

end=$(date +%s.%N)
runtime=$(python -c "print(${end} - ${start})")

echo "Runtime was $runtime seconds."

# For Ubuntu
# java -cp "atom-1.14.jar:." atomSimulation.Main 200 5 10 100
# javac -cp "atom-1.14.jar:." -d . application/src/atomSimulation/Main.java application/src/atomSimulation/InformedAgent.java application/src/atomSimulation/NoiseAgent.java
