#!/bin/bash

start=$(date +%s.%N)
# Add permissions: chmod +x script.sh
# Run script: ./script.sh

mkdir -p csvs
mkdir -p plots/csvs
mkdir results

# Remove the csv files autogenerated from previous run & pictures
rm -f csvs/*
rm -f plots/csvs/*

# Compile the Java program
javac -cp atom-1.14.jar src/Main.java src/NoiseAgent.java src/InformedAgent.java src/MarketMaker.java src/InformationPair.java

ROOT_FOLDER=$(dirname "$(realpath "$0")")
export PYTHONPATH=$ROOT_FOLDER

# For loop for our simulations
# Set the number of times to repeat the commands (number of simulations)
n=50
days=40

persons=${1:-1000}
informed=${2:-2}
aggressivity=${3:-10}
threshold=${4:-0.5}
risk_limit=${5:-0.02}

# Single tag used consistently across all filenames and Python calls
tag="${persons}_${informed}_g${aggressivity}_t${threshold}_r${risk_limit}"

echo "Running bash script with:"
echo "  persons=$persons, informed=$informed%, aggressivity=$aggressivity"
echo "  threshold=$threshold, risk_limit=$risk_limit"
echo "  tag=$tag"

javaPart() {
  local i=$1

  java -classpath "src:atom-1.14.jar" Main \
    "$persons" "$informed" "$aggressivity" "$days" "$i" \
    "$threshold" "$risk_limit"

  cat "csvs/data$i.csv" | grep "^Price" > "plots/csvs/prices${i}${tag}.csv"
  cat "csvs/data$i.csv" | grep "^\(Agent\|Day\).*" > "plots/csvs/agents$i.csv"
  sed -i '/noname/d' "plots/csvs/prices${i}${tag}.csv"
}

callJava() {
  echo "Start Java Simulation..."
  for i in $(seq 1 $n); do
      javaPart "$i" &
  done
  wait
}

pythonGraphMetricsPart() {
  total_rows=$(cat "plots/csvs/prices1${tag}.csv" | wc -l)
  big_granularity=$((total_rows / 50)) # low frequency
  small_granularity=$((total_rows / 700)) # high frequency

  echo "Total rows: $total_rows, Big Granularity: $big_granularity, Small Granularity: $small_granularity"
  echo "Start Python Computation (Network metrics part)..."

  python "$ROOT_FOLDER"/plots/monte-carlo/graph_metrics.py \
    $n "$tag" $big_granularity $small_granularity $days
  echo -e "Metrics graphs were generated.\n"
}

pythonAgentCashPart() {
  echo "Start Python Computation (Agents' Cash Part)..."

  # Run the Python program for plotting agents' cash
  python "$ROOT_FOLDER"/plots/monte-carlo/agent_cash.py $n "$persons" "$informed" $days
  echo -e "Agents' cash evolution graph was generated. \n"
}

pythonLaplacianMetricsPart() {
  echo "Start Python Computation (Laplacian Metrics Part)..."

  # Run the Python program for computing laplacian metrics
  python "$ROOT_FOLDER"/plots/monte-carlo/laplacian_metrics.py $n "$persons" "$informed"
  echo -e "Laplacian graph was generated. \n"
}

pythonVisualGraphs() {
  total_rows=$(cat "plots/csvs/prices1${tag}.csv" | wc -l)
  big_granularity=$((total_rows / 50)) # low frequency
  small_granularity=$((total_rows / 700)) # high frequency

  echo "Start Python Computation (Graph Visuals)..."
  python plots/monte-carlo/visualize_graphs.py \
    $n "$tag" $big_granularity $small_granularity
  echo -e "Graph visuals were generated. \n"
}

pythonBucketSensitivity() {
  echo "Start Python Computation (Bucket-size Sensitivity)..."
  python "$ROOT_FOLDER"/plots/monte-carlo/bucket_sensitivity.py \
    $n "$tag" $days
  echo -e "Bucket-size sensitivity analysis was generated.\n"
}

callJava

# ~ 15 minutes
pythonGraphMetricsPart

# ~ 1 minute
pythonAgentCashPart

# ~ 1 minute
pythonVisualGraphs

# HEATMAP Generation
pythonBucketSensitivity

end=$(date +%s.%N)
runtime=$(python -c "print(${end} - ${start})")

echo "Runtime was $runtime seconds."
